### Загрузка данных

In [1]:
import pandas as pd

# Загрузка данных
file_path = './Titanic.csv'
data = pd.read_csv(file_path)

# Просмотр первых строк данных
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Переменные содержат числовые, категориальные и текстовые типы данных.

### Предварительный анализ данных

In [2]:
# Общая информация о данных
data_info = data.info()

# Описательная статистика для числовых признаков
numeric_stats = data.describe()

# Уникальные значения в категориальных признаках
categorical_columns = data.select_dtypes(include=['object']).columns
unique_values = {col: data[col].unique() for col in categorical_columns}

data_info, numeric_stats, unique_values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

(None,
        PassengerId    Survived      Pclass         Age       SibSp  \
 count   418.000000  418.000000  418.000000  332.000000  418.000000
 mean   1100.500000    0.363636    2.265550   30.272590    0.447368
 std     120.810458    0.481622    0.841838   14.181209    0.896760
 min     892.000000    0.000000    1.000000    0.170000    0.000000
 25%     996.250000    0.000000    1.000000   21.000000    0.000000
 50%    1100.500000    0.000000    3.000000   27.000000    0.000000
 75%    1204.750000    1.000000    3.000000   39.000000    1.000000
 max    1309.000000    1.000000    3.000000   76.000000    8.000000

             Parch        Fare
 count  418.000000  417.000000
 mean     0.392344   35.627188
 std      0.981429   55.907576
 min      0.000000    0.000000
 25%      0.000000    7.895800
 50%      0.000000   14.454200
 75%      0.000000   31.500000
 max      9.000000  512.329200  ,
 {'Name': array(['Kelly, Mr. James', 'Wilkes, Mrs. James (Ellen Needs)',
         'Myles, Mr. Thomas Francis', 'Wirz, Mr. Albert',
         'Hirvonen, Mrs. Alexander (Helga E Lindqvist)',
         'Svensson, Mr. Johan Cervin', 'Connolly, Miss. Kate',
         'Caldwell, Mr. Albert Francis',
         'Abrahim, Mrs. Joseph (Sophie Halaut Easu)',
         'Davies, Mr. John Samuel', 'Ilieff, Mr. Ylio',
         'Jones, Mr. Charles Cresson',
         'Snyder, Mrs. John Pillsbury (Nelle Stevenson)',
         'Howard, Mr. Benjamin',
         'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)',
         'del Carlo, Mrs. Sebastiano (Argenia Genovesi)',
         'Keane, Mr. Daniel', 'Assaf, Mr. Gerios',
         'Ilmakangas, Miss. Ida Livija',
         'Assaf Khalil, Mrs. Mariana (Miriam")"', 'Rothschild, Mr. Martin',
         'Olsen, Master. Artur Karl',
         'Flegenheim, Mrs. Alfred (Antoinette)',
         'Williams, Mr. Richard Norris II',
         'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)',
         'Robins, Mr. Alexander A', 'Ostby, Miss. Helene Ragnhild',
         'Daher, Mr. Shedid', 'Brady, Mr. John Bertram',
         'Samaan, Mr. Elias', 'Louch, Mr. Charles Alexander',
         'Jefferys, Mr. Clifford Thomas',
         'Dean, Mrs. Bertram (Eva Georgetta Light)',
         'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"',
         'Mock, Mr. Philipp Edmund',
         'Katavelas, Mr. Vassilios (Catavelas Vassilios")"',
         'Roth, Miss. Sarah A', 'Cacic, Miss. Manda', 'Sap, Mr. Julius',
         'Hee, Mr. Ling', 'Karun, Mr. Franz', 'Franklin, Mr. Thomas Parham',
         'Goldsmith, Mr. Nathan', 'Corbett, Mrs. Walter H (Irene Colvin)',
         'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)',
         'Peltomaki, Mr. Nikolai Johannes', 'Chevre, Mr. Paul Romaine',
         'Shaughnessy, Mr. Patrick',
         'Bucknell, Mrs. William Robert (Emma Eliza Ward)',
         'Coutts, Mrs. William (Winnie Minnie" Treanor)"',
         'Smith, Mr. Lucien Philip', 'Pulbaum, Mr. Franz',
         'Hocking, Miss. Ellen Nellie""', 'Fortune, Miss. Ethel Flora',
         'Mangiavacchi, Mr. Serafino Emilio', 'Rice, Master. Albert',
         'Cor, Mr. Bartol', 'Abelseth, Mr. Olaus Jorgensen',
         'Davison, Mr. Thomas Henry', 'Chaudanson, Miss. Victorine',
         'Dika, Mr. Mirko', 'McCrae, Mr. Arthur Gordon',
         'Bjorklund, Mr. Ernst Herbert', 'Bradley, Miss. Bridget Delia',
         'Ryerson, Master. John Borie',
         'Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)',
         'Burns, Miss. Mary Delia', 'Moore, Mr. Clarence Bloomfield',
         'Tucker, Mr. Gilbert Milligan Jr',
         'Fortune, Mrs. Mark (Mary McDougald)', 'Mulvihill, Miss. Bertha E',
         'Minkoff, Mr. Lazar', 'Nieminen, Miss. Manta Josefina',
         'Ovies y Rodriguez, Mr. Servando', 'Geiger, Miss. Amalie',
         'Keeping, Mr. Edwin', 'Miles, Mr. Frank',
         'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)',
         'Aldworth, Mr. Charles Augustus', 'Doyle, Miss. Elizabeth',
         'Boulos, Master. Akar', 'Straus, Mr. Isidor',
         'Case, Mr. Howard Brown', 'Demetri, Mr. Marinko',
         'Lamb, Mr. John Joseph', 'Khalil, Mr. Betros',
         'Barry, Miss. Julia', 'Badman, Miss. Emily Louisa',
         "O'Donoghue, Ms. Bridget", 'Wells, Master. Ralph Lester',
         'Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)',
         'Pedersen, Mr. Olaf', 'Davidson, Mrs. Thornton (Orian Hays)',
         'Guest, Mr. Robert', 'Birnbaum, Mr. Jakob',
         'Tenglin, Mr. Gunnar Isidor',
         'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)',
         'Makinen, Mr. Kalle Edvard', 'Braf, Miss. Elin Ester Maria',
         'Nancarrow, Mr. William Henry',
         'Stengel, Mrs. Charles Emil Henry (Annie May Morris)',
         'Weisz, Mr. Leopold', 'Foley, Mr. William',
         'Johansson Palmquist, Mr. Oskar Leander',
         'Thomas, Mrs. Alexander (Thamine Thelma")"',
         'Holthen, Mr. Johan Martin', 'Buckley, Mr. Daniel',
         'Ryan, Mr. Edward', 'Willer, Mr. Aaron (Abi Weller")"',
         'Swane, Mr. George', 'Stanton, Mr. Samuel Ward',
         'Shine, Miss. Ellen Natalia', 'Evans, Miss. Edith Corse',
         'Buckley, Miss. Katherine',
         'Straus, Mrs. Isidor (Rosalie Ida Blun)',
         'Chronopoulos, Mr. Demetrios', 'Thomas, Mr. John',
         'Sandstrom, Miss. Beatrice Irene', 'Beattie, Mr. Thomson',
         'Chapman, Mrs. John Henry (Sara Elizabeth Lawry)',
         'Watt, Miss. Bertha J', 'Kiernan, Mr. John',
         'Schabert, Mrs. Paul (Emma Mock)', 'Carver, Mr. Alfred John',
         'Kennedy, Mr. John', 'Cribb, Miss. Laura Alice',
         'Brobeck, Mr. Karl Rudolf', 'McCoy, Miss. Alicia',
         'Bowenur, Mr. Solomon', 'Petersen, Mr. Marius',
         'Spinner, Mr. Henry John', 'Gracie, Col. Archibald IV',
         'Lefebre, Mrs. Frank (Frances)', 'Thomas, Mr. Charles P',
         'Dintcheff, Mr. Valtcho', 'Carlsson, Mr. Carl Robert',
         'Zakarian, Mr. Mapriededer', 'Schmidt, Mr. August',
         'Drapkin, Miss. Jennie', 'Goodwin, Mr. Charles Frederick',
         'Goodwin, Miss. Jessie Allis', 'Daniels, Miss. Sarah',
         'Ryerson, Mr. Arthur Larned', 'Beauchamp, Mr. Henry James',
         'Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey")"',
         'Vander Planke, Mr. Julius', 'Hilliard, Mr. Herbert Henry',
         'Davies, Mr. Evan', 'Crafton, Mr. John Bertram',
         'Lahtinen, Rev. William', 'Earnshaw, Mrs. Boulton (Olive Potter)',
         'Matinoff, Mr. Nicola', 'Storey, Mr. Thomas',
         'Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)',
         'Asplund, Master. Filip Oscar', 'Duquemin, Mr. Joseph',
         'Bird, Miss. Ellen', 'Lundin, Miss. Olga Elida',
         'Borebank, Mr. John James', 'Peacock, Mrs. Benjamin (Edith Nile)',
         'Smyth, Miss. Julia', 'Touma, Master. Georges Youssef',
         'Wright, Miss. Marion', 'Pearce, Mr. Ernest',
         'Peruschitz, Rev. Joseph Maria',
         'Kink-Heilmann, Mrs. Anton (Luise Heilmann)', 'Brandeis, Mr. Emil',
         'Ford, Mr. Edward Watson',
         'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)',
         'Hellstrom, Miss. Hilda Maria', 'Lithman, Mr. Simon',
         'Zakarian, Mr. Ortin', 'Dyker, Mr. Adolf Fredrik',
         'Torfa, Mr. Assad', 'Asplund, Mr. Carl Oscar Vilhelm Gustafsson',
         'Brown, Miss. Edith Eileen', 'Sincock, Miss. Maude',
         'Stengel, Mr. Charles Emil Henry',
         'Becker, Mrs. Allen Oliver (Nellie E Baumgardner)',
         'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)',
         'McCrie, Mr. James Matthew', 'Compton, Mr. Alexander Taylor Jr',
         'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)',
         'Lane, Mr. Patrick',
         'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)',
         'Maybery, Mr. Frank Hubert',
         'Phillips, Miss. Alice Frances Louisa', 'Davies, Mr. Joseph',
         'Sage, Miss. Ada', 'Veal, Mr. James', 'Angle, Mr. William A',
         'Salomon, Mr. Abraham L', 'van Billiard, Master. Walter John',
         'Lingane, Mr. John', 'Drew, Master. Marshall Brines',
         'Karlsson, Mr. Julius Konrad Eugen',
         'Spedden, Master. Robert Douglas', 'Nilsson, Miss. Berta Olivia',
         'Baimbrigge, Mr. Charles Robert',
         'Rasmussen, Mrs. (Lena Jacobsen Solvang)', 'Murphy, Miss. Nora',
         'Danbom, Master. Gilbert Sigvard Emanuel',
         'Astor, Col. John Jacob', 'Quick, Miss. Winifred Vera',
         'Andrew, Mr. Frank Thomas', 'Omont, Mr. Alfred Fernand',
         'McGowan, Miss. Katherine', 'Collett, Mr. Sidney C Stuart',
         'Rosenbaum, Miss. Edith Louise', 'Delalic, Mr. Redjo',
         'Andersen, Mr. Albert Karvin', 'Finoli, Mr. Luigi',
         'Deacon, Mr. Percy William',
         'Howard, Mrs. Benjamin (Ellen Truelove Arman)',
         'Andersson, Miss. Ida Augusta Margareta', 'Head, Mr. Christopher',
         'Mahon, Miss. Bridget Delia', 'Wick, Mr. George Dennick',
         'Widener, Mrs. George Dunton (Eleanor Elkins)',
         'Thomson, Mr. Alexander Morrison',
         'Duran y More, Miss. Florentina', 'Reynolds, Mr. Harold J',
         'Cook, Mrs. (Selena Rogers)', 'Karlsson, Mr. Einar Gervasius',
         'Candee, Mrs. Edward (Helen Churchill Hungerford)',
         'Moubarek, Mrs. George (Omine Amenia" Alexander)"',
         'Asplund, Mr. Johan Charles', 'McNeill, Miss. Bridget',
         'Everett, Mr. Thomas James', 'Hocking, Mr. Samuel James Metcalfe',
         'Sweet, Mr. George Frederick', 'Willard, Miss. Constance',
         'Wiklund, Mr. Karl Johan', 'Linehan, Mr. Michael',
         'Cumings, Mr. John Bradley', 'Vendel, Mr. Olof Edvin',
         'Warren, Mr. Frank Manley', 'Baccos, Mr. Raffull',
         'Hiltunen, Miss. Marta',
         'Douglas, Mrs. Walter Donald (Mahala Dutton)',
         'Lindstrom, Mrs. Carl Johan (Sigrid Posse)',
         'Christy, Mrs. (Alice Frances)', 'Spedden, Mr. Frederic Oakley',
         'Hyman, Mr. Abraham', 'Johnston, Master. William Arthur Willie""',
         'Kenyon, Mr. Frederick R', 'Karnes, Mrs. J Frank (Claire Bennett)',
         'Drew, Mr. James Vivian',
         'Hold, Mrs. Stephen (Annie Margaret Hill)',
         'Khalil, Mrs. Betros (Zahie Maria" Elias)"',
         'West, Miss. Barbara J',
         'Abrahamsson, Mr. Abraham August Johannes',
         'Clark, Mr. Walter Miller', 'Salander, Mr. Karl Johan',
         'Wenzel, Mr. Linhart', 'MacKay, Mr. George William',
         'Mahon, Mr. John', 'Niklasson, Mr. Samuel',
         'Bentham, Miss. Lilian W', 'Midtsjo, Mr. Karl Albert',
         'de Messemaeker, Mr. Guillaume Joseph',
         'Nilsson, Mr. August Ferdinand',
         'Wells, Mrs. Arthur Henry (Addie" Dart Trevaskis)"',
         'Klasen, Miss. Gertrud Emilia',
         'Portaluppi, Mr. Emilio Ilario Giuseppe', 'Lyntakoff, Mr. Stanko',
         'Chisholm, Mr. Roderick Robert Crispin',
         'Warren, Mr. Charles William', 'Howard, Miss. May Elizabeth',
         'Pokrnic, Mr. Mate', 'McCaffry, Mr. Thomas Francis',
         'Fox, Mr. Patrick',
         'Clark, Mrs. Walter Miller (Virginia McDowell)',
         'Lennon, Miss. Mary', 'Saade, Mr. Jean Nassr',
         'Bryhl, Miss. Dagmar Jenny Ingeborg ',
         'Parker, Mr. Clifford Richard', 'Faunthorpe, Mr. Harry',
         'Ware, Mr. John James', 'Oxenham, Mr. Percy Thomas',
         'Oreskovic, Miss. Jelka', 'Peacock, Master. Alfred Edward',
         'Fleming, Miss. Honora', 'Touma, Miss. Maria Youssef',
         'Rosblom, Miss. Salli Helena', 'Dennis, Mr. William',
         'Franklin, Mr. Charles (Charles Fardon)',
         'Snyder, Mr. John Pillsbury', 'Mardirosian, Mr. Sarkis',
         'Ford, Mr. Arthur', 'Rheims, Mr. George Alexander Lucien',
         'Daly, Miss. Margaret Marcella Maggie""', 'Nasr, Mr. Mustafa',
         'Dodge, Dr. Washington', 'Wittevrongel, Mr. Camille',
         'Angheloff, Mr. Minko', 'Laroche, Miss. Louise',
         'Samaan, Mr. Hanna', 'Loring, Mr. Joseph Holland',
         'Johansson, Mr. Nils', 'Olsson, Mr. Oscar Wilhelm',
         'Malachard, Mr. Noel', 'Phillips, Mr. Escott Robert',
         'Pokrnic, Mr. Tome', 'McCarthy, Miss. Catherine Katie""',
         'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)',
         'Allison, Mr. Hudson Joshua Creighton',
         'Aks, Master. Philip Frank', 'Hays, Mr. Charles Melville',
         'Hansen, Mrs. Claus Peter (Jennie L Howard)',
         'Cacic, Mr. Jego Grga', 'Vartanian, Mr. David',
         'Sadowitz, Mr. Harry', 'Carr, Miss. Jeannie',
         'White, Mrs. John Stuart (Ella Holmes)', 'Hagardon, Miss. Kate',
         'Spencer, Mr. William Augustus', 'Rogers, Mr. Reginald Harry',
         'Jonsson, Mr. Nils Hilding', 'Jefferys, Mr. Ernest Wilfred',
         'Andersson, Mr. Johan Samuel', 'Krekorian, Mr. Neshan',
         'Nesson, Mr. Israel', 'Rowe, Mr. Alfred G',
         'Kreuchen, Miss. Emilie', 'Assam, Mr. Ali',
         'Becker, Miss. Ruth Elizabeth',
         'Rosenshine, Mr. George (Mr George Thorne")"',
         'Clarke, Mr. Charles Valentine', 'Enander, Mr. Ingvar',
         'Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) ',
         'Dulles, Mr. William Crothers', 'Thomas, Mr. Tannous',
         'Nakid, Mrs. Said (Waika Mary" Mowad)"', 'Cor, Mr. Ivan',
         'Maguire, Mr. John Edward', 'de Brito, Mr. Jose Joaquim',
         'Elias, Mr. Joseph', 'Denbury, Mr. Herbert',
         'Betros, Master. Seman', 'Fillbrook, Mr. Joseph Charles',
         'Lundstrom, Mr. Thure Edvin', 'Sage, Mr. John George',
         'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)',
         'van Billiard, Master. James William',
         'Abelseth, Miss. Karen Marie', 'Botsford, Mr. William Hull',
         'Whabee, Mrs. George Joseph (Shawneene Abi-Saab)',
         'Giles, Mr. Ralph', 'Walcroft, Miss. Nellie',
         'Greenfield, Mrs. Leo David (Blanche Strouse)',
         'Stokes, Mr. Philip Joseph', 'Dibden, Mr. William',
         'Herman, Mr. Samuel', 'Dean, Miss. Elizabeth Gladys Millvina""',
         'Julian, Mr. Henry Forbes',
         'Brown, Mrs. John Murray (Caroline Lane Lamson)',
         'Lockyer, Mr. Edward', "O'Keefe, Mr. Patrick",
         'Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)',
         'Sage, Master. William Henry',
         'Mallet, Mrs. Albert (Antoinette Magnin)',
         'Ware, Mrs. John James (Florence Louise Long)',
         'Strilic, Mr. Ivan',
         'Harder, Mrs. George Achilles (Dorothy Annan)',
         'Sage, Mrs. John (Annie Bullen)', 'Caram, Mr. Joseph',
         'Riihivouri, Miss. Susanna Juhantytar Sanni""',
         'Gibson, Mrs. Leonard (Pauline C Boeson)',
         'Pallas y Castello, Mr. Emilio', 'Giles, Mr. Edgar',
         'Wilson, Miss. Helen Alice', 'Ismay, Mr. Joseph Bruce',
         'Harbeck, Mr. William H', 'Dodge, Mrs. Washington (Ruth Vidaver)',
         'Bowen, Miss. Grace Scott', 'Kink, Miss. Maria',
         'Cotterill, Mr. Henry Harry""', 'Hipkins, Mr. William Edward',
         'Asplund, Master. Carl Edgar', "O'Connor, Mr. Patrick",
         'Foley, Mr. Joseph', 'Risien, Mrs. Samuel (Emma)',
         "McNamee, Mrs. Neal (Eileen O'Leary)",
         'Wheeler, Mr. Edwin Frederick""', 'Herman, Miss. Kate',
         'Aronsson, Mr. Ernst Axel Algot', 'Ashby, Mr. John',
         'Canavan, Mr. Patrick', 'Palsson, Master. Paul Folke',
         'Payne, Mr. Vivian Ponsonby',
         'Lines, Mrs. Ernest H (Elizabeth Lindsey James)',
         'Abbott, Master. Eugene Joseph', 'Gilbert, Mr. William',
         'Kink-Heilmann, Mr. Anton',
         'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)',
         'Colbert, Mr. Patrick',
         'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)',
         'Larsson-Rondberg, Mr. Edvard A', 'Conlon, Mr. Thomas Henry',
         'Bonnell, Miss. Caroline', 'Gale, Mr. Harry',
         'Gibson, Miss. Dorothy Winifred', 'Carrau, Mr. Jose Pedro',
         'Frauenthal, Mr. Isaac Gerald',
         'Nourney, Mr. Alfred (Baron von Drachstedt")"',
         'Ware, Mr. William Jeffery', 'Widener, Mr. George Dunton',
         'Riordan, Miss. Johanna Hannah""', 'Peacock, Miss. Treasteall',
         'Naughton, Miss. Hannah',
         'Minahan, Mrs. William Edward (Lillian E Thorpe)',
         'Henriksson, Miss. Jenny Lovisa', 'Spector, Mr. Woolf',
         'Oliva y Ocana, Dona. Fermina', 'Saether, Mr. Simon Sivertsen',
         'Ware, Mr. Frederick', 'Peter, Master. Michael J'], dtype=object),
  'Sex': array(['male', 'female'], dtype=object),
  'Ticket': array(['330911', '363272', '240276', '315154', '3101298', '7538',
         '330972', '248738', '2657', 'A/4 48871', '349220', '694', '21228',
         '24065', 'W.E.P. 5734', 'SC/PARIS 2167', '233734', '2692',
         'STON/O2. 3101270', '2696', 'PC 17603', 'C 17368', 'PC 17598',
         'PC 17597', 'PC 17608', 'A/5. 3337', '113509', '2698', '113054',
         '2662', 'SC/AH 3085', 'C.A. 31029', 'C.A. 2315', 'W./C. 6607',
         '13236', '2682', '342712', '315087', '345768', '1601', '349256',
         '113778', 'SOTON/O.Q. 3101263', '237249', '11753',
         'STON/O 2. 3101291', 'PC 17594', '370374', '11813', 'C.A. 37671',
         '13695', 'SC/PARIS 2168', '29105', '19950', 'SC/A.3 2861',
         '382652', '349230', '348122', '386525', '349232', '237216',
         '347090', '334914', 'F.C.C. 13534', '330963', '113796', '2543',
         '382653', '349211', '3101297', 'PC 17562', '113503', '359306',
         '11770', '248744', '368702', '2678', 'PC 17483', '19924', '349238',
         '240261', '2660', '330844', 'A/4 31416', '364856', '29103',
         '347072', '345498', 'F.C. 12750', '376563', '13905', '350033',
         '19877', 'STON/O 2. 3101268', '347471', 'A./5. 3338', '11778',
         '228414', '365235', '347070', '2625', 'C 4001', '330920', '383162',
         '3410', '248734', '237734', '330968', 'PC 17531', '329944', '2680',
         '2681', 'PP 9549', '13050', 'SC/AH 29037', 'C.A. 33595', '367227',
         '392095', '368783', '371362', '350045', '367226', '211535',
         '342441', 'STON/OQ. 369943', '113780', '4133', '2621', '349226',
         '350409', '2656', '248659', 'SOTON/OQ 392083', 'CA 2144', '113781',
         '244358', '17475', '345763', '17463', 'SC/A4 23568', '113791',
         '250651', '11767', '349255', '3701', '350405', '347077',
         'S.O./P.P. 752', '347469', '110489', 'SOTON/O.Q. 3101315',
         '335432', '2650', '220844', '343271', '237393', '315153',
         'PC 17591', 'W./C. 6608', '17770', '7548', 'S.O./P.P. 251', '2670',
         '2673', '29750', 'C.A. 33112', '230136', 'PC 17756', '233478',
         '113773', '7935', 'PC 17558', '239059', 'S.O./P.P. 2', 'A/4 48873',
         'CA. 2343', '28221', '226875', '111163', 'A/5. 851', '235509',
         '28220', '347465', '16966', '347066', 'C.A. 31030', '65305',
         '36568', '347080', 'PC 17757', '26360', 'C.A. 34050', 'F.C. 12998',
         '9232', '28034', 'PC 17613', '349250', 'SOTON/O.Q. 3101308',
         'S.O.C. 14879', '347091', '113038', '330924', '36928', '32302',
         'SC/PARIS 2148', '342684', 'W./C. 14266', '350053', 'PC 17606',
         '2661', '350054', '370368', 'C.A. 6212', '242963', '220845',
         '113795', '3101266', '330971', 'PC 17599', '350416', '110813',
         '2679', '250650', 'PC 17761', '112377', '237789', '3470', '17464',
         '26707', 'C.A. 34651', 'SOTON/O2 3101284', '13508', '7266',
         '345775', 'C.A. 42795', 'AQ/4 3130', '363611', '28404', '345501',
         '345572', '350410', 'C.A. 34644', '349235', '112051', 'C.A. 49867',
         'A. 2. 39186', '315095', '368573', '370371', '2676', '236853',
         'SC 14888', '2926', 'CA 31352', 'W./C. 14260', '315085', '364859',
         '370129', 'A/5 21175', 'SOTON/O.Q. 3101314', '2655', 'A/5 1478',
         'PC 17607', '382650', '2652', '33638', '345771', '349202',
         'SC/Paris 2123', '113801', '347467', '347079', '237735', '315092',
         '383123', '112901', '392091', '12749', '350026', '315091', '2658',

1. **Общая информация о данных**:
   - Датасет содержит 418 строк и 12 столбцов.
   - Типы данных включают числовые (`int64`, `float64`) и строковые (`object`).
   - Столбцы с пропусками: `Age` (332 непустых значений), `Fare` (417), `Cabin` (91).

2. **Описательная статистика числовых признаков**:
   - Основные метрики, такие как среднее значение, стандартное отклонение и диапазон, рассчитаны.

3. **Уникальные значения категориальных признаков**:
   - `Sex`: `['male', 'female']`.
   - `Embarked`: `['Q', 'S', 'C']`.
   - `Cabin` имеет множество уникальных значений, многие из которых отсутствуют (`NaN`).

### Выявление пропусков в данных

In [4]:
# Выявление пропусков в данных
missing_values = data.isnull().sum()
missing_values_percentage = (missing_values / len(data)) * 100

missing_info = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage (%)': missing_values_percentage
}).sort_values(by='Percentage (%)', ascending=False)

missing_info

             Missing Values  Percentage (%)
Cabin                   327       78.229665
Age                      86       20.574163
Fare                      1        0.239234
PassengerId               0        0.000000
Survived                  0        0.000000
Pclass                    0        0.000000
Name                      0        0.000000
Sex                       0        0.000000
SibSp                     0        0.000000
Parch                     0        0.000000
Ticket                    0        0.000000
Embarked                  0        0.000000

Обработка пропусков:

1. **`Cabin`**:
   - Пропущенные данные: 78.23%.
   - Решение: Исключить данный столбец из анализа, так как большинство значений отсутствует.

2. **`Age`**:
   - Пропущенные данные: 20.57%.
   - Решение: Заполнить пропуски средним значением или медианой, чтобы сохранить информацию.

3. **`Fare`**:
   - Пропущенные данные: 0.24%.
   - Решение: Заполнить пропуск средним или медианой.

In [5]:
# Удаление столбца Cabin
data_cleaned = data.drop(columns=['Cabin'])

# Заполнение пропусков в Age медианой
age_median = data_cleaned['Age'].median()
data_cleaned['Age'].fillna(age_median, inplace=True)

# Заполнение пропуска в Fare медианой
fare_median = data_cleaned['Fare'].median()
data_cleaned['Fare'].fillna(fare_median, inplace=True)

# Проверка на оставшиеся пропуски
remaining_missing = data_cleaned.isnull().sum()

remaining_missing

<ipython-input-5-25a198c8cd80>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['Age'].fillna(age_median, inplace=True)
<ipython-input-5-25a198c8cd80>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_cleaned['Fare'].fillna(fare_median, inplace=True)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Выявление категориальных признаков

In [6]:
# Определение категориальных признаков
categorical_features = data_cleaned.select_dtypes(include=['object']).columns.tolist()

categorical_features

['Name', 'Sex', 'Ticket', 'Embarked']

Преобразование категориальных данных:
Признаки Sex и Embarked будут преобразованы с использованием One-Hot Encoding.
Признаки Name и Ticket могут быть исключены или обработаны по-другому, в зависимости от их значимости для анализа.

### Преобразование категориальных данных

In [8]:
# One-Hot Encoding для категориальных признаков Sex и Embarked
data_encoded = pd.get_dummies(data_cleaned, columns=['Sex', 'Embarked'], drop_first=True)

# Исключение признаков Name и Ticket для упрощения анализа
data_encoded = data_encoded.drop(columns=['Name', 'Ticket'])

data_encoded.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,892,0,3,34.5,0,0,7.8292,True,True,False
1,893,1,3,47.0,1,0,7.0000,False,False,True
2,894,0,2,62.0,0,0,9.6875,True,True,False
3,895,0,3,27.0,0,0,8.6625,True,False,True
4,896,1,3,22.0,1,1,12.2875,False,False,True

### Нормализация числовых данных

In [9]:
from sklearn.preprocessing import MinMaxScaler

# Нормализация числовых данных
scaler = MinMaxScaler()
numerical_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
data_encoded[numerical_features] = scaler.fit_transform(data_encoded[numerical_features])

data_encoded.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,892,0,1.0,0.452723,0.000,0.000000,0.015282,True,True,False
1,893,1,1.0,0.617566,0.125,0.000000,0.013663,False,False,True
2,894,0,0.5,0.815377,0.000,0.000000,0.018909,True,True,False
3,895,0,1.0,0.353818,0.000,0.000000,0.016908,True,False,True
4,896,1,1.0,0.287881,0.125,0.111111,0.023984,False,False,True

### Генерация новых признаков на основе существующих данных

In [10]:
# Генерация нового признака: общая семья (SibSp + Parch)
data_encoded['FamilySize'] = data_encoded['SibSp'] + data_encoded['Parch']

# Генерация нового признака: одинокий пассажир
data_encoded['IsAlone'] = (data_encoded['FamilySize'] == 0).astype(int)

# Проверка данных после генерации новых признаков
data_encoded.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,FamilySize,IsAlone
0,892,0,1.0,0.452723,0.000,0.000000,0.015282,True,True,False,0.000000,1
1,893,1,1.0,0.617566,0.125,0.000000,0.013663,False,False,True,0.125000,0
2,894,0,0.5,0.815377,0.000,0.000000,0.018909,True,True,False,0.000000,1
3,895,0,1.0,0.353818,0.000,0.000000,0.016908,True,False,True,0.000000,1
4,896,1,1.0,0.287881,0.125,0.111111,0.023984,False,False,True,0.236111,0

Новые признаки :
1. **FamilySize** — общий размер семьи на борту (сумма `SibSp` и `Parch`).
2. **IsAlone** — индикатор, является ли пассажир одиноким.

### Отбор сгенерированных признаков для финального набора данных

In [11]:
# Оценка корреляции признаков
correlation_matrix = data_encoded.corr()

# Отбор признаков с высокой корреляцией с целевой переменной (Survived)
high_correlation_features = correlation_matrix['Survived'][abs(correlation_matrix['Survived']) > 0.1].index.tolist()

# Удаление целевой переменной из списка
high_correlation_features.remove('Survived')

high_correlation_features

['Pclass',
 'Parch',
 'Fare',
 'Sex_male',
 'Embarked_Q',
 'Embarked_S',
 'FamilySize',
 'IsAlone']